[package]
name = "atomic"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-generate.workspace = true
anyhow.workspace = true
clap.workspace = true
tempfile.workspace = true
indoc.workspace = true
git2.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
