#!/usr/bin/env python3
"""Machine-written verdicts: one ``verdict.json`` beside every packet.

``task.json`` accreted 73 distinct keys across 97 packets, and the field now
called ``pipeline_note`` used to be called ``status`` while mixing pipeline
position (``S2_SPEC``, ``REOPENED_S3``) with conclusions (``QUALIFIED``,
``REJECTED_E1``), so no reader could tell a decision from a waypoint. Worse, the same measurement was recorded under different names:
``reference_pass_rate`` in 56 packets, ``reference_score`` in 35,
``reference.pass_rate`` in 2.

This module derives one verdict per packet from what is measurable today and
writes it next to the packet. Every evidence slot carries the ``task.json`` key
it was read from, so a number can be traced back rather than trusted. Slots
with no source are named in ``evidence_pending`` instead of being defaulted to
a passing-looking value.

The output is generated, not authored: ``--check`` recomputes every file and
fails on any difference, which is what makes a hand edit visible.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from harness.core import layout, verify_task

BANNER = "generated by harness/core/verdict.py -- do not edit by hand"
GATE = "harness/core/verify_task.py"
FILENAME = "verdict.json"

# The six slots the tier line is meant to rest on. A packet is not held back for
# missing any of them -- the static gate decides the tier -- but a missing slot
# is stated so that reviewing evidence does not mean re-reading 73 keys.
SLOTS = ("reference_pass", "dummy_pass", "candidate_score", "adjusted_gap",
         "mutation", "coverage_gap")


def load_json(path: Path) -> dict:
    """Read a packet file. Four ``task.json`` carry a UTF-8 BOM, which plain
    ``utf-8`` decoding rejects; every reader here must tolerate it."""
    return json.loads(path.read_bytes().decode("utf-8-sig"))


def _first(task: dict, *keys: str):
    """The first key present, with the key name, so the value stays traceable."""
    for key in keys:
        if "." in key:
            head, _, tail = key.partition(".")
            outer = task.get(head)
            if isinstance(outer, dict) and tail in outer:
                return outer[tail], key
        elif key in task:
            return task[key], key
    return None, None


def _rate(value):
    """A pass rate from either a bare number or a ``{passed, total}`` pair."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return round(float(value), 4)
    if isinstance(value, dict):
        total = value.get("total")
        passed = value.get("passed")
        if isinstance(total, (int, float)) and total and isinstance(passed, (int, float)):
            return round(passed / total, 4)
    return None


def _reference_pass(task):
    return _first(task, "reference_pass_rate", "reference_score", "reference.pass_rate")


def _dummy_pass(task):
    return _first(task, "dummy_score", "dummy_pass_rate", "controls.dummy")


def _candidate_score(task):
    return _first(task, "candidate_score", "candidate_evaluation", "score_distribution")


def _adjusted_gap(task):
    return _first(task, "integration_gap", "true_gap_events")


def _mutation(task):
    return _first(task, "mutation", "mutation_status")


def _coverage_gap(task):
    return _first(task, "coverage_gap", "coverage")


EXTRACTORS = {
    "reference_pass": _reference_pass,
    "dummy_pass": _dummy_pass,
    "candidate_score": _candidate_score,
    "adjusted_gap": _adjusted_gap,
    "mutation": _mutation,
    "coverage_gap": _coverage_gap,
}


def evidence_of(task: dict) -> tuple[dict, list[str]]:
    evidence: dict[str, dict] = {}
    pending: list[str] = []
    for name in SLOTS:
        value, source = EXTRACTORS[name](task)
        if source is None:
            pending.append(name)
            continue
        slot = {"from": f"task.json:{source}", "value": value}
        rate = _rate(value)
        if rate is not None:
            slot["rate"] = rate
        evidence[name] = slot
    return evidence, pending


def static_of(task_id: str) -> tuple[list[str], list[str]]:
    """``check_task`` returns ``(errors, warnings)`` despite its annotation."""
    result = verify_task.check_task(task_id)
    errors, warnings = result if isinstance(result, tuple) else (result, [])
    return list(errors), list(warnings)


def build(task_id: str) -> dict:
    packet = layout.task_dir(task_id)
    if packet is None:
        raise SystemExit(f"no packet under tasks/<language>/ for {task_id}")
    task = load_json(packet / "task.json")
    errors, warnings = static_of(task_id)
    evidence, pending = evidence_of(task)
    verdict = {
        "_": BANNER,
        "instance_id": task_id,
        "language": layout.language_of(task_id),
        "static": {
            "gate": GATE,
            "verdict": "fail" if errors else "pass",
            "errors": errors,
            "warnings": warnings,
        },
        "tier": "wip" if errors else "tasks",
        "tier_reason": errors[0] if errors else "the static gate passes",
        "evidence": evidence,
        "evidence_pending": pending,
    }
    # Provenance, not a decision. Values like REVALIDATION-REQUIRED record where
    # the packet sat in the pipeline, which the static tier does not express.
    # The field was called `status`, which is why it kept being read as a
    # verdict; under its own name it can be carried without being mistaken.
    if "pipeline_note" in task:
        verdict["pipeline_note"] = task["pipeline_note"]
    return verdict


def render(verdict: dict) -> str:
    return json.dumps(verdict, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    write = "--write" in argv
    selected = [a for a in argv if not a.startswith("-")] or layout.task_ids()
    if not (check or write):
        print("usage: python harness/core/verdict.py [--write|--check] [task_id ...]",
              file=sys.stderr)
        return 2
    drift, tiers = [], {"tasks": 0, "wip": 0}
    for task_id in selected:
        verdict = build(task_id)
        tiers[verdict["tier"]] += 1
        path = layout.task_dir(task_id) / FILENAME
        text = render(verdict)
        if write:
            path.write_text(text, encoding="utf-8")
        elif not path.exists():
            drift.append(f"{task_id}: no {FILENAME}")
        elif path.read_text(encoding="utf-8") != text:
            drift.append(f"{task_id}: {FILENAME} differs from the generator")
    for line in drift:
        print(f"- {line}")
    print(f"summary: {tiers['tasks']} tasks, {tiers['wip']} wip, "
          f"{len(drift)} drifted of {len(selected)}")
    return 1 if drift else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
