import os
import sys
import unittest
sys.path.insert(0, '.')
from pycparser import c_parser, c_generator, c_ast, parse_file
from .test_util import cpp_supported, cpp_path, cpp_args
_c_parser = c_parser.CParser()

def compare_asts(ast1, ast2):
    """Compares two ASTs recursively just enough for the purpose of testing.

    Since this function is recursive it also accepts non-ast parameters, in
    which case it compares them literally (with ==) or recursively (for tuples
    or lists).
    """
    if type(ast1) is not type(ast2):
        return False
    elif isinstance(ast1, (list, tuple)):
        if len(ast1) != len(ast2):
            return False
        for i in range(len(ast1)):
            if not compare_asts(ast1[i], ast2[i]):
                return False
        return True
    elif isinstance(ast1, c_ast.Node):
        for attr in ast1.attr_names:
            attr1 = getattr(ast1, attr)
            attr2 = getattr(ast2, attr)
            if not compare_asts(attr1, attr2):
                return False
        children1 = ast1.children()
        children2 = ast2.children()
        if len(children1) != len(children2):
            return False
        for i in range(len(children1)):
            if not compare_asts(children1[i], children2[i]):
                return False
        return True
    else:
        return ast1 == ast2

def parse_to_ast(src):
    return _c_parser.parse(src)

class TestFunctionDeclGeneration(unittest.TestCase):

    class _FuncDeclVisitor(c_ast.NodeVisitor):

        def __init__(self):
            self.stubs = []

        def visit_FuncDecl(self, node):
            gen = c_generator.CGenerator()
            self.stubs.append(gen.visit(node))

    def test_partial_funcdecl_generation(self):
        src = '\n            void noop(void);\n            void *something(void *thing);\n            int add(int x, int y);'
        ast = parse_to_ast(src)
        v = TestFunctionDeclGeneration._FuncDeclVisitor()
        v.visit(ast)
        self.assertEqual(len(v.stubs), 3)
        self.assertTrue('void noop(void)' in v.stubs)
        self.assertTrue('void *something(void *thing)' in v.stubs)
        self.assertTrue('int add(int x, int y)' in v.stubs)

class TestCtoC(unittest.TestCase):

    def _run_c_to_c(self, src, *args, **kwargs):
        ast = parse_to_ast(src)
        generator = c_generator.CGenerator(*args, **kwargs)
        return generator.visit(ast)

    def _assert_ctoc_correct(self, src, *args, **kwargs):
        """Checks that the c2c translation was correct by parsing the code
        generated by c2c for src and comparing the AST with the original
        AST.

        Additional arguments are passed to CGenerator.__init__.
        """
        src2 = self._run_c_to_c(src, *args, **kwargs)
        self.assertTrue(compare_asts(parse_to_ast(src), parse_to_ast(src2)), '{!r} != {!r}'.format(src, src2))
        return src2

    def test_complex_decls(self):
        self._assert_ctoc_correct('int** (*a)(void);')
        self._assert_ctoc_correct('int** (*a)(void*, int);')
        self._assert_ctoc_correct('int (*b)(char * restrict k, float);')
        self._assert_ctoc_correct('int (*b)(char * _Atomic k, float);')
        self._assert_ctoc_correct('int (*b)(char * _Atomic volatile k, float);')
        self._assert_ctoc_correct('int test(const char* const* arg);')
        self._assert_ctoc_correct('int test(const char** const arg);')

    def test_alignment(self):
        self._assert_ctoc_correct('_Alignas(32) int b;')
        self._assert_ctoc_correct('int _Alignas(32) a;')
        self._assert_ctoc_correct('_Alignas(32) _Atomic(int) b;')
        self._assert_ctoc_correct('_Atomic(int) _Alignas(32) b;')
        self._assert_ctoc_correct('_Alignas(long long) int a;')
        self._assert_ctoc_correct('int _Alignas(long long) a;')
        self._assert_ctoc_correct('\n            typedef struct node_t {\n                _Alignas(64) void* next;\n                int data;\n            } node;\n            ')
        self._assert_ctoc_correct('\n            typedef struct node_t {\n                void _Alignas(64) * next;\n                int data;\n            } node;\n            ')

    def test_casts(self):
        self._assert_ctoc_correct('\n            int main() {\n                int b = (int) f;\n                int c = (int*) f;\n            }')
        self._assert_ctoc_correct('\n            int main() {\n                int a = (int) b + 8;\n                int t = (int) c;\n            }\n        ')

    def test_initlist(self):
        self._assert_ctoc_correct('int arr[] = {1, 2, 3};')

    def test_exprs(self):
        self._assert_ctoc_correct('\n            int main(void)\n            {\n                int a;\n                int b = a++;\n                int c = ++a;\n                int d = a--;\n                int e = --a;\n            }')

    def test_krstyle(self):
        self._assert_ctoc_correct('\n            int main(argc, argv)\n            int argc;\n            char** argv;\n            {\n                return 0;\n            }\n        ')

    def test_nest_initializer_list(self):
        self._assert_ctoc_correct('\n        int main()\n        {\n           int i[1][1] = { { 1 } };\n        }')

    def test_nest_named_initializer(self):
        self._assert_ctoc_correct('struct test\n            {\n                int i;\n                struct test_i_t\n                {\n                    int k;\n                } test_i;\n                int j;\n            };\n            struct test test_var = {.i = 0, .test_i = {.k = 1}, .j = 2};\n        ')

    def test_expr_list_in_initializer_list(self):
        self._assert_ctoc_correct('\n        int main()\n        {\n           int i[1] = { (1, 2) };\n        }')

    def test_issue36(self):
        self._assert_ctoc_correct('\n            int main() {\n            }')

    def test_issue37(self):
        self._assert_ctoc_correct('\n            int main(void)\n            {\n              unsigned size;\n              size = sizeof(size);\n              return 0;\n            }')

    def test_issue66(self):
        self._assert_ctoc_correct('\n            struct foo;\n            ')
        self._assert_ctoc_correct('\n            struct foo {};\n            ')

    def test_issue83(self):
        self._assert_ctoc_correct('\n            void x(void) {\n                int i = (9, k);\n            }\n            ')

    def test_issue84(self):
        self._assert_ctoc_correct('\n            void x(void) {\n                for (int i = 0;;)\n                    i;\n            }\n            ')

    def test_issue246(self):
        self._assert_ctoc_correct('\n            int array[3] = {[0] = 0, [1] = 1, [1+1] = 2};\n            ')

    def test_noreturn(self):
        self._assert_ctoc_correct('\n            _Noreturn int x(void) {\n                abort();\n            }\n            ')

    def test_exprlist_with_semi(self):
        self._assert_ctoc_correct('\n            void x() {\n                if (i < j)\n                    tmp = C[i], C[i] = C[j], C[j] = tmp;\n                if (i <= j)\n                    i++, j--;\n            }\n        ')

    def test_exprlist_with_compound(self):
        self._assert_ctoc_correct('\n            void test(){\n                (sizeof (0), ({ if (0) ; else ; }));\n            }\n        ')

    def test_exprlist_with_subexprlist(self):
        self._assert_ctoc_correct('\n            void x() {\n                (a = b, (b = c, c = a));\n            }\n        ')

    def test_comma_operator_funcarg(self):
        self._assert_ctoc_correct('\n            void f(int x) { return x; }\n            int main(void) { f((1, 2)); return 0; }\n        ')

    def test_comma_op_in_ternary(self):
        self._assert_ctoc_correct('\n            void f() {\n                (0, 0) ? (0, 0) : (0, 0);\n            }\n        ')

    def test_comma_op_assignment(self):
        self._assert_ctoc_correct('\n            void f() {\n                i = (a, b, c);\n            }\n        ')

    def test_compound_literal(self):
        self._assert_ctoc_correct('char **foo = (char *[]){ "x", "y", "z" };')
        self._assert_ctoc_correct('int i = ++(int){ 1 };')
        self._assert_ctoc_correct('struct foo_s foo = (struct foo_s){ 1, 2 };')

    def test_enum(self):
        self._assert_ctoc_correct('\n            enum e\n            {\n              a,\n              b = 2,\n              c = 3\n            };\n        ')
        self._assert_ctoc_correct('\n            enum f\n            {\n                g = 4,\n                h,\n                i\n            };\n        ')

    def test_enum_typedef(self):
        self._assert_ctoc_correct('typedef enum EnumName EnumTypedefName;')

    def test_generate_struct_union_enum_exception(self):
        self._assert_ctoc_correct('struct TestStruct { int value; };')

    def test_array_decl(self):
        self._assert_ctoc_correct('int g(const int a[const 20]){}')
        self._assert_ctoc_correct('const int a[const 20];')

    def test_atomic_qual(self):
        self._assert_ctoc_correct('_Atomic int x;')
        self._assert_ctoc_correct('_Atomic int* x;')
        self._assert_ctoc_correct('int* _Atomic x;')
        s1 = '_Atomic(int) x;'
        self._assert_ctoc_correct(s1)
        s2 = '_Atomic(int*) x;'
        self._assert_ctoc_correct(s2)
        s3 = '_Atomic(_Atomic(int)*) x;'
        self._assert_ctoc_correct(s3)
        s4 = 'typedef _Atomic(int) atomic_int;'
        self._assert_ctoc_correct(s4)
        s5 = 'typedef _Atomic(_Atomic(_Atomic(int (*)(void)) *) *) t;'
        self._assert_ctoc_correct(s5)
        self._assert_ctoc_correct('\n            typedef struct node_t {\n                _Atomic(void*) a;\n                _Atomic(void) *b;\n                _Atomic void *c;\n            } node;\n            ')

    def test_nested_sizeof(self):
        src = '1'
        for _ in range(30):
            src = 'sizeof(' + src + ')'
        src = 'int x = ' + src + ';'
        self._assert_ctoc_correct(src)
if __name__ == '__main__':
    unittest.main()
