[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-generate.workspace = true
anyhow.workspace = true
assert_cmd.workspace = true
bstr.workspace = true
clap.workspace = true
env_logger.workspace = true
git2.workspace = true
gix-config.workspace = true
indoc.workspace = true
log.workspace = true
names.workspace = true
predicates.workspace = true
tempfile.workspace = true
time.workspace = true
url.workspace = true

[[bin]]
name = "cargo-generate"
path = "src/bin/cargo-generate.rs"
